name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: ["11.*", "12.*", "13.*"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: "11.*"
            testbench: ^9.0
          - laravel: "12.*"
            testbench: ^10.11
          - laravel: "13.*"
            testbench: ^11.1
        exclude:
          - laravel: "11.*"
            php: 8.5
          - laravel: "13.*"
            php: 8.2

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, fileinfo
          coverage: none

      - name: Allow EOL Laravel 11 for compatibility testing
        if: matrix.laravel == '11.*'
        run: composer config audit.block-insecure false

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
